version: '3.7'

services:

  conferencedb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=conferenceDB
    networks:
      - default
